// React/src/components/InvoiceTable/InvoiceList/InvoiceItem/InvoiceItem.js
import React from "react";

import "./InvoiceItem.css";

const InvoiceItem = ({ id, index, name, count, price, onDelete }) => (
  <tr>
    <td>{index}.</td>
    <td className="item-name">{name}</td>
    <td>{count}</td>
    <td className="units">шт.</td>
    <td className="price">{(+price).toLocaleString()}</td>
    <td className="price">{(price * count).toLocaleString()}</td>
    <td className="printHide delete" onClick={() => onDelete(id)}>
      x
    </td>
  </tr>
);

export default InvoiceItem;

// Svelte/src/components/InvoiceTable/InvoiceList/InvoiceItem/InvoiceItem.svelte
<script>
  export let index;
  export let name;
  export let count;
  export let price;
  export let onDelete;
</script>

<style>
  .delete {
    text-align: center !important;

    visibility: hidden;
    text-transform: uppercase;
    font-weight: bold;
    color: brown;

    cursor: pointer;
  }

  .delete:focus,
  .delete:hover {
    background-color: aquamarine;
  }
</style>

<tr>
  <td>{index}.</td>
  <td class="item-name">{name}</td>
  <td>{count}</td>
  <td class="units">шт.</td>
  <td class="price">{(+price).toLocaleString()}</td>
  <td class="price">{(price * count).toLocaleString()}</td>
  <td class="printHide delete" on:click={onDelete}>x</td>
</tr>
