// Svelte/src/components/Footer.svelte
<style>
  .printBtn {
    display: flex;
    margin: 2rem auto;
  }
</style>

<table id="subscripts">
  <tbody>
    <tr>
      <th>Отпустил</th>
      <td>&nbsp;</td>
      <th>Получил</th>
      <td>&nbsp;</td>
    </tr>
  </tbody>
</table>
<button class="printBtn printHide" on:click={() => window.print()}>
  Печать
</button>

// React/src/components/Footer/Footer.js
import React from "react";

import "./Footer.css";

const Footer = () => (
  <>
    <table id="subscripts">
      <tbody>
        <tr>
          <th>Отпустил</th>
          <td>&nbsp;</td>
          <th>Получил</th>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
    <button className="printBtn printHide" onClick={() => window.printpage()}>
      Печать
    </button>
  </>
);

export default Footer;
